#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config

echo -e "Alien [SERVER] [V.1] (run help)\n"

while :
do
	read -r -e MAIN

	case $MAIN in
		help)
			echo -e "help: this message"
			echo -e "exit: exit"
			echo -e "pass: set password"
			echo -e "start: start the server"
			echo -e "stop: stop the server"
			;;
		pass)
			mkdir -p $DIRMAIN/gpg
			touch $DIRMAIN/gpg/pass
			echo -e "enter a passphrase used to encrypt and decrypt everything (this needs to be transfered to the clients later)"
			echo -e "hint: smash your keyboard for best results"
			read -r -e ENTER_PASS
			echo $ENTER_PASS > $DIRMAIN/gpg/pass
			echo -e "done."
			;;
		exit)
			echo -e "killing the server..."
			killall "socat" > /dev/null 2>&1
			exit
			;;
		start)
			if [[ ! -d "$DIRMAIN/gpg" ]];
			then
				echo -e "please run \"pass\" first"
			else
				echo -e "starting server"
				mkdir -p $DIRMAIN/chat
				mkdir -p $DIRMAIN/files
				mkdir -p $DIRMAIN/.tmp
				touch $DIRMAIN/chat/main
				if [[ ! -f "$DIRMAIN/chat/main.gpg" ]];
				then
					gpg -c --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/gpg/pass $DIRMAIN/chat/main > /dev/null 2>&1
				fi

				#output

				socat -U tcp-l:$PORT,fork,reuseaddr open:"$DIRMAIN/chat/main.gpg" &

				#input

				while :
				do
					socat -u tcp-listen:$IPORT,reuseaddr open:"$DIRMAIN/.tmp/tmp.gpg",creat || break
					gpg -d -q -o $DIRMAIN/.tmp/tmp --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/gpg/pass $DIRMAIN/.tmp/tmp.gpg
					rm -f $DIRMAIN/.tmp/tmp.gpg

					case $(head -n 1 $DIRMAIN/.tmp/tmp) in
						"MSG")
							date "+%T | %d.%m.%Y" >> $DIRMAIN/chat/main
							sed 1d $DIRMAIN/.tmp/tmp >> $DIRMAIN/chat/main
							echo -e "------------" >> $DIRMAIN/chat/main
							rm -f $DIRMAIN/.tmp/tmp
							gpg -c --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/gpg/pass $DIRMAIN/chat/main > /dev/null 2>&1
						;;
						"DOW")
							while :
							do
								touch $DIRMAIN/.tmp/d_lock
								ls -A $DIRMAIN/files | gpg -c --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/gpg/pass | socat tcp-l:$UPORT,reuseaddr,reuseport - | gpg -q -d --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/gpg/pass -
								socat tcp-l:$UPORT,reuseaddr,reuseport - | gpg -q -d --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/gpg/pass - >> $DIRMAIN/.tmp/file_call
								gpg -c -o - --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/gpg/pass $DIRMAIN/files/$(cat $DIRMAIN/.tmp/file_call) | socat tcp-l:$UPORT,reuseaddr,reuseport -
								rm -f $DIRMAIN/.tmp/file_call
								rm -f $DIRMAIN/.tmp/file.gpg
								rm -f $DIRMAIN/.tmp/tmp
								break
								rm -f $DIRMAIN/.tmp/d_lock
							done &
						;;
						*)
							echo -e "CRITICAL: Message Header format unknown, dont know how to proceed"
							rm -f $DIRMAIN/.tmp/tmp
						;;
					esac
				done &

			fi
			;;
		stop)
			echo -e "killing the server..."
			killall "socat" > /dev/null 2>&1
			;;
		*)
			echo -e "unknown command"
			;;
	esac
done
